### ISSUE TITLE
port RouteTime UI to Tracking

### ISSUE THREAD

**Issue by wjalal** [NafiuRahman77/BusBuddy-Client-End#30]
- [x] follow mockUI (UI are mostly similar in these two)
- [x] copy all elements that are common
- [x] (mainly changing variable from routeTimeData to trackingData)
- [ ] #64
- [ ] stations should be shown with some sort of marker (different from start and end) regardless of where the path is 
- [ ] change target, destination and current loc8n markers
