### ISSUE TITLE
tracking time prediction and delay

### ISSUE THREAD

**Issue by wjalal** [NafiuRahman77/BusBuddy-Client-End#64]
backend: 

- [x] create timestamp window
- [ ] make path for all routes 
- [x] @WJGalib station checking order has to be reversed based on trip direction 

frontend:

- [x] update time list continuously in view
- [x] implement calculation
- [ ] calculate S from path?? 
- [ ] time interpolation
- [ ] show user default station

 algorithm :slightly_smiling_face: : 

![photo_2024-02-16_19-19-56](https://github.com/100100guy/BusBuddy-Client-End/assets/11938012/44ecb1a8-945f-4423-ac60-76e4ad99002a)
